{"name": "test_logind", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure.Test_login object at 0x000001661986C7C0>\n\n    @allure.story(\"密码错误，登录失败\")\n    @allure.link(\"https://blog.csdn.net/weixin_44275820/article/details/105169871\",name=\"我的博客\")\n    @allure.severity(allure.severity_level.MINOR)    #不太重要\n    def test_logind(self):\n        with allure.step(\"点击用户名输入框\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击输入密码输入框\"):\n            print(\"输入密码\")\n        print(\"点击登录按钮\")\n        with allure.step(\"点击登录后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure.py:39: AssertionError"}, "steps": [{"name": "点击用户名输入框", "status": "passed", "start": 1628850867988, "stop": 1628850867989}, {"name": "点击输入密码输入框", "status": "passed", "start": 1628850867989, "stop": 1628850867989}, {"name": "点击登录后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\GIT\\jenkins\\pytest\\test_allure.py\", line 39, in test_logind\n    assert \"1\" == 1\n"}, "start": 1628850867989, "stop": 1628850867990}], "start": 1628850867988, "stop": 1628850867990, "uuid": "fee495fa-8d8e-49fd-9c31-8d12e82bd23c", "historyId": "88f9f8bae1d76194820ce90e08256cbd", "testCaseId": "d5004451f38917497e7e23b7381ace99", "fullName": "test_allure.Test_login#test_logind", "labels": [{"name": "story", "value": "密码错误，登录失败"}, {"name": "feature", "value": "This is AI testcase"}, {"name": "severity", "value": "minor"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "LAPTOP-LEG04IAI"}, {"name": "thread", "value": "17748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}], "links": [{"type": "link", "url": "https://blog.csdn.net/weixin_44275820/article/details/105169871", "name": "我的博客"}]}