{"name": "test_logind", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_AI.Test_login object at 0x000002B0D92C16D0>\n\n    @allure.story(\"密码错误，登录失败\")\n    @allure.link(\"https://blog.csdn.net/weixin_44275820/article/details/105169871\",name=\"我的博客\")\n    @allure.severity(allure.severity_level.MINOR)    #不太重要\n    def test_logind(self):\n        with allure.step(\"点击用户名输入框\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击输入密码输入框\"):\n            print(\"输入密码\")\n        print(\"点击登录按钮\")\n        with allure.step(\"点击登录后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_AI.py:39: AssertionError"}, "steps": [{"name": "点击用户名输入框", "status": "passed", "start": 1628851433303, "stop": 1628851433303}, {"name": "点击输入密码输入框", "status": "passed", "start": 1628851433303, "stop": 1628851433303}, {"name": "点击登录后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\GIT\\jenkins\\pytest\\test_AI.py\", line 39, in test_logind\n    assert \"1\" == 1\n"}, "start": 1628851433303, "stop": 1628851433303}], "start": 1628851433302, "stop": 1628851433303, "uuid": "12e51b67-9dcd-460a-ba36-7e7791432689", "historyId": "dfbe894686552bb09f4d4023c4f4bd58", "testCaseId": "bfc1ec014ce0786f9f06714406a50b89", "fullName": "test_AI.Test_login#test_logind", "labels": [{"name": "feature", "value": "This is AI testcase"}, {"name": "story", "value": "密码错误，登录失败"}, {"name": "severity", "value": "minor"}, {"name": "suite", "value": "test_AI"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "LAPTOP-LEG04IAI"}, {"name": "thread", "value": "19504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_AI"}], "links": [{"type": "link", "url": "https://blog.csdn.net/weixin_44275820/article/details/105169871", "name": "我的博客"}]}